flujo/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<int:flujo_id>/', views.ver_fase, name='ver_fase'),
    path('ver/', views.ver_flujo, name='ver_flujo'),
    path('crear/', views.Crear_Flujo, name='crear_flujo'),
    path('<int:pk>/modificar/', views.Modificar_Flujo, name='modificar_flujo'),
    path('<int:pk>/eliminar/', views.Eliminar_Flujo, name='eliminar_flujo'),
    # path('<int:pk>/modificar/', views.Modificar_Flujo3, name='modificar_flujo3'),
    #path('crear/fase/', views.Crear_Fase2, name='crear_fase2'),
    #path('crear/fase/', views.Fase3, name='fase3'),
]

gestorProyectos/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls, name = 'home'),
    path('proyecto/', include('proyecto.urls')),
    path('usuario/', include('usuarios.urls')),
    path('', include('login.urls')),
    path('rol/', include('roles_permisos.urls')),
    path('cliente/', include('cliente.urls')),
    path('sprint/', include('sprint.urls')),
    path('flujo/', include('flujo.urls')),
]

tipo_us/urls.py
from django.urls import path, include
from .views import *


urlpatterns = [
    path('',ListaTUSView.as_view(), name='tipoushome'),
    path('importar/',ListaTUSImportarView.as_view(), name='listaimportar'),
    path('crear/',CrearTUSView.as_view(), name='creartipous'),
    path('crear/crear_campo/', CrearCampoPersonalizadoView.as_view(), name='crearcampopersonalizado'),
    path('<int:pk>/', DetalleTUSView.as_view(), name='detalletipous'),
    path('<int:pk>/modificar/', Modificar, name='modificartipous'),
    path('importar/<int:pk>/', ImportarTUSView, name='importartipous'),
    #path('eliminar/<int:pk>',EliminarTUSView, name='eliminartipous'),
    #path('modificar/<int:pk>/eliminar_campo/',EliminarCampoPersonalizadoView.as_view(), name='eliminarcampopersonalizado'),
    path('<int:pk>/flujo/', include('flujo.urls'), name='redireccionarflujo')
]

flujo/models.py
from django.db import models
from tipo_us.models import Tipo_US


class Flujo(models.Model):

    nombre = models.CharField(max_length=100, unique=True)
    """Nombre del flujo"""
    tipo = models.ForeignKey(Tipo_US, on_delete=models.CASCADE, null=True, blank=False)
    """Una clave foranea del Tipo de User Story al cual el flujo pertenece"""
    cant_fases = models.IntegerField(default=0)
    """La cantidad de fases que tiene el flujo"""

    def __str__(self):
        return f' {self.nombre}'


class Fase(models.Model):

    nombre = models.CharField(max_length=100, unique=True)
    """El nombre de la fase"""
    id_flujo = models.ForeignKey('flujo.Flujo', related_name='flujo', on_delete=models.SET_NULL, null=True, blank=False)
    """Una clave foranea del flujo al cual pertenece esta fase"""
    indice = models.IntegerField(null=True, blank=True)
    """Como las fases son secuenciales y no se pueden pasar a la ultima fase porque si, este atributo
    sirve para indicar en que posicion de la secuencialidad de fases del flujo se encuentra"""

    def __str__(self):
        return f' {self.nombre}'

tipo_us/models.py
from django.db import models
from proyecto.models import Proyecto
from sprint.models import Sprint


class CampoPersonalizado(models.Model):
    """
    CampoPersonalizado es el modelo que almacena los campos personalizados de los tipos de user story
    """
    nombre_campo = models.CharField(max_length=100)
    """Indica el nombre que va a tener el field o campo"""
    tipo_dato = models.CharField(max_length=100, default='TEXT')
    """Indica el tipo de dato que tendra el campo por defecto es texto(TEXT) o CharField"""
    proyecto_or = models.IntegerField(null=True)
    """Indica el proyecto en el que fue creado"""


class Tipo_US(models.Model):

    nombre = models.CharField(max_length=100, unique=True)
    """Indica el nombre del tipo de user story"""
    proyecto = models.ForeignKey(Proyecto, on_delete=models.CASCADE, null=True)
    """Proyecto al cual pertenece el tipo de User Story"""
    # sprint = models.ForeignKey(Sprint, on_delete=models.CASCADE, null=True, blank=True, default=None)

    def __str__(self):
        return f'{self.nombre}'

    #def set_sprint(self, sprint_id):
     #   self.sprint = Sprint.objects.get(pk=sprint_id)
      #  self.save()
       # return


class Tipo_Campo(models.Model):
    """
    Este modelo contiene al tipo y al campo personalizado de dicho tipo lo cual representa una relación de muchos a muchos de tipos con campos.
    """
    tipo = models.ForeignKey(Tipo_US, on_delete= models.CASCADE, null=True)
    """Clave foranea del tipo de user story"""
    campo = models.ForeignKey(CampoPersonalizado, on_delete=models.CASCADE)
    """Clave foranea del campo personalizado del tipo"""

    def __str__(self):
        return f'{self.campo.nombre_campo}'


class US_Tipo_Campo_Valor(models.Model):
    """
    Este modelo sirve para poder relacionar el user story con el tipo y los campos con sus respectivos valores
    """
    us = models.ForeignKey('user_story.UserStory', on_delete=models.CASCADE, null=True)
    """clave foranea del modelo  user_story"""
    tipo_campo = models.ForeignKey(Tipo_Campo, on_delete=models.CASCADE)
    """clave foranea del modelo Tipo_Campo para obtener los campos del tipo de user story"""
    valor = models.CharField(max_length=100)
    """indica el valor para un determinado campo en el us"""

tipo_us/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render
from django.utils.decorators import method_decorator

from .forms import *
from .models import *
from django.views.generic import CreateView,UpdateView, ListView,DeleteView, DetailView
from django.shortcuts import reverse, get_object_or_404
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from flujo.models import *
from user_story.models import *
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
# Create your views here.


@method_decorator(login_required, name='dispatch')
class CrearTUSView(SuccessMessageMixin, CreateView):
    """
    Vista de creación de tipo de user story, contiene un enlace para agregar campos personalizados
    guardar y cancelar, solo el scrum master del proyecto puede acceder a esta vista
    :parameter proyecto_id: indica el id del proyecto donde se crea el tipo de user story
    :return al presionar guardar, retornara la vista de crear flujos
    :return al presionar cancelar volvera a la vista anterior

    """
    model = Tipo_US
    template_name = "tipous/crear.html"
    form_class = Tipo_USForm
    success_message = " %(nombre)s se ha creado exitosamente"

    #def get_success_message(self, cleaned_data):
    def get_form_kwargs(self):
        """
        con este metodo podemos pasarle parametros como kwargs al formulario
        :return kwargs con el valor añadido
        """
        kwargs = super(CrearTUSView, self).get_form_kwargs()

        # La variable que queremos pasar al formulario
        kwargs.update({'proyecto_id': self.kwargs.get('proyecto_id')})

        return kwargs

    def get_success_url(self):
        """
        Sirve para indicar la ruta de redireccion que tomara la vista
        :return reverse('crear_flujo', kwargs={'proyecto_id': self.kwargs.get('proyecto_id'), 'pk': self.object.id})
        """
        return reverse('crear_flujo', kwargs={'proyecto_id': self.kwargs.get('proyecto_id'), 'pk': self.object.id})

    def get_context_data(self, **kwargs):
        """
        Cargamos en el contexto los argumentos recividos para poder usarlos en la plantilla
        :param kwargs: argumentos del contexto
        :return context
        """
        # Llamamos ala implementacion primero del  context
        context = super(CrearTUSView, self).get_context_data(**kwargs)
        # Agregamos el id a la plantilla
        context['proyecto_id'] = self.kwargs.get('proyecto_id')
        return context

    def form_valid(self, form):
        """
        con form_valid poder hacer ciertas operaciones con los datos del formulario antes de guardarlo
        :param form: formulario con los datos POSTeados y validos
        :return super().form_valid(form) guarda los datos del formulario y redirecciona al valor especificado
        con get_success_url()
        """
        tipo_nuevo = form.save()
        proyecto = Proyecto.objects.get(pk = self.kwargs.get('proyecto_id'))
        tipo_nuevo.proyecto = proyecto
        #cargamos el tipo en tipo_campo
        campos_por_tipo = Tipo_Campo.objects.filter(tipo__isnull = True)
        for campo in campos_por_tipo:
            if campo.campo.proyecto_or == proyecto.id:
                campo.tipo = tipo_nuevo
                campo.save()

        return super().form_valid(form)

# este no está en Modificar


@method_decorator(login_required, name='dispatch')
class ModificarTUSView(UpdateView):

    model = Tipo_US
    template_name = "tipous/editar.html"
    form_class = Tipo_USForm

    # success_url = '/'


    def form_valid(self, form, **kwargs):
        # return HttpResponseRedirect('/proyecto/'+ self.proyecto_id)
        return HttpResponseRedirect(reverse('ver_proyecto', kwargs={'proyecto_id': self.kwargs.get('proyecto_id')}))

    def get_context_data(self, **kwargs):
        # Llamamos ala implementacion primero del  context
        context = super(ModificarTUSView, self).get_context_data(**kwargs)
        # Agregamos el id a la plantilla
        context['proyecto_id'] = self.kwargs.get('proyecto_id')
        context['pk'] = self.kwargs.get('pk')
        return context


@login_required()
def Modificar(request,proyecto_id, pk):
    """
    vista de modificacion de tipo de user story
    esta vista no se utiliza ya que los tipos no se pueden modificar una vez creados
    :param request: datos de la vista
    :param proyecto_id: id del proyecto al cual pertenece el tipo
    :param pk: id del tipo a modificar
    """
    tipo_us = Tipo_US.objects.get(pk=pk)
    if request.method == 'POST':

        form = Tipo_USForm(request.POST, instance = tipo_us)

        if form.is_valid():
            # lista de tcv del tipo de us actual
            lista_tcv = Tipo_Campo.objects.filter(tipo = tipo_us)

            #query = CampoPersonalizado.objects.filter(tipo_us=tipo_us)
            #print(lista_tcv)

            form.save()
            return HttpResponseRedirect(reverse('tipoushome', kwargs={'proyecto_id': proyecto_id } ))
    else:
        form = Tipo_USForm(instance=tipo_us)
    return render(request, "tipous/editar.html", {'form': form, 'proyecto_id':proyecto_id, 'pk':pk })


@method_decorator(login_required, name='dispatch')
class CrearCampoPersonalizadoView(CreateView):
    """
    Vista de creación de nuevo campo personalizado, esta vista se llama desde la vista de creación de tipo
    permite crear varios campos personalizados con sus tipos correspondientes
    al presionar cancelar vuelve a la vista de creación de tipo de user story
    """
    model = CampoPersonalizado
    template_name = "tipous/crear_campo.html"
    form_class = CampoPersonalizadoForm

    def get_success_url(self):
        """
        url de redirección cuando los datos son válidos
        :return /proyecto/proyecto_id/tipo-us/crear/crear_campo/
        """
        return reverse('crearcampopersonalizado', kwargs={'proyecto_id': self.kwargs.get('proyecto_id')})

    def get_context_data(self, **kwargs):
        """
        En este metodo se añaden nuevos datos al contexto de la plantilla
        se le añade el id del proyecto
        :param kwargs: datos pasados por la url ej:proyecto_id
        :return context el nuevo contexto con los nuevos datos.
        """
        # Llamamos ala implementacion primero del  context
        context = super(CrearCampoPersonalizadoView, self).get_context_data(**kwargs)
        # Agregamos el id a la plantilla
        context['proyecto_id'] = self.kwargs.get('proyecto_id')
        #context['pk'] = self.kwargs.get('pk')
        return context

    def form_valid(self, form):
        """
        Con este metodo se añade el proyecto al campo creado y se carga la tabla tipo_campo
        :param form: formulario con los datos POSTeados y validos
        :return super().form_valid(form) guarda y redirecciona a la url especificada en get_success_url()
        """
        nombre_campo = form.cleaned_data.get('nombre_campo')

        # print(nombre_campo)
        #tipopk = self.kwargs.get('pk')

        #tipo_objeto = Tipo_US.objects.get(pk = tipopk)
        newcampo = form.save()
        newcampo.proyecto_or = self.kwargs.get('proyecto_id')
        tcv = Tipo_Campo(campo=newcampo)
        tcv.save()
        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class ListaTUSView(ListView):

    """
    Esta vista sirve para lista los tipos de user story
    """
    model = Tipo_US
    context_object_name = 'tipos_campos'
    template_name = "tipous/tipo_us_list.html"

    def get_success_url(self):
        """
        url de redirección cuando los datos son válidos
        :return /proyecto/proyecto_id/
        """
        return reverse('ver_proyecto', kwargs={'proyecto_id': self.kwargs.get('proyecto_id')})

    def get_queryset(self):
        """
        sirve para elegir los datos que se le pasaran a la plantilla como queryset
        se filtra por proyecto_id
        :return queryset
        """
        return Tipo_US.objects.filter(proyecto_id = self.kwargs.get('proyecto_id'))

    def get_context_data(self, **kwargs):
        """
        En este metodo se añaden nuevos datos al contexto de la plantilla
        se le añade el id del proyecto
        :param kwargs: datos pasados por la url ej:proyecto_id
        :return context el nuevo contexto con los nuevos datos.
        """
        # Llamamos ala implementacion primero del  context
        context = super(ListaTUSView, self).get_context_data(**kwargs)
        # Agregamos el id a la plantilla
        context['proyecto_id'] = self.kwargs.get('proyecto_id')
        context['importar'] = False
        us=UserStory.objects.all()
        context['us']=us
        return context


@method_decorator(login_required, name='dispatch')
class DetalleTUSView(DetailView):
    """
    sirve para obtener los datos del tipo que se envia como solicitud
    """
    model = Tipo_US
    template_name = "tipous/detalle.html"

    def get_context_data(self, **kwargs):
        """
        se añaden los datos que se pasaran como contexto a la plantilla
        proyecto_id, pk:id del tipo a mostrar, tipo: objeto tipo
        :param kwargs: [], argumentos pasados al metodo o la clase
        :return: context contexto con los datos añadidos
        """
        # Llamamos ala implementacion primero del  context
        context = super(DetalleTUSView, self).get_context_data(**kwargs)
        #tipo = Tipo_US.objects.get(pk = self.kwargs.get('pk'))
        # Agregamos el id a la plantilla
        context['proyecto_id'] = self.kwargs.get('proyecto_id')
        context['pk'] = self.kwargs.get('pk')
        # context['tipo'] = tipo

        return context


@login_required()
def ImportarTUSView(request, proyecto_id, pk):
    """
    Vista que permite modificar los datos del tipo de user story a importar,

tipo_us/templates/tipous/confirm_import.html
{% extends 'proyecto/base.html' %}

{% block title %}
    <title>Importar Tipo US</title>
{% endblock %}


{% block content %}

    <form method="post">
    {% csrf_token %}
        Se importara el tipo "{{ tipo }}"
        ¿estas seguro que deseas importar?
            <input type="submit" value="Submit"/>
            <a class="btn btn-secondary" href="{% url 'tipoushome' proyecto_id %}">Cancelar</a>
    </form>

{% endblock %}

tipo_us/templates/tipous/crear.html
{% extends 'proyecto/base.html' %}

{% block title %}
    <title>Registrar Tipo US</title>
{% endblock %}


{% block content %}

    <h1 class="co-md-4 col-md-offset-4">   Nuevo Tipo de User Story</h1>
    <form method="post">
    {% csrf_token %}
        <div class="row1">
            <div class="col-md-4 col-md-offset-4">
                <div class="input-group">
                    {{ form.as_p }}
                </div>
            </div>
        </div>

        <div class="row1">
            <div class="col-md-4 col-md-offset-4">
                <div class="form-group">
                    <button class="btn btn-primary" type="submit">Guardar</button>
                    <a class="btn btn-link" href="{% url 'crearcampopersonalizado' proyecto_id  %}">Nuevo Campo </a>
                    <a class="btn btn-secondary" href="{% url 'ver_proyecto'  proyecto_id  %}">Cancelar</a>
                </div>
            </div>
        </div>

    </form>

{% endblock %}

tipo_us/templates/tipous/crear_campo.html
{% extends 'proyecto/base.html' %}

    {% block content %}
        <form  method="post">
            {% csrf_token %}
            <div class="row1">
                <div class="col-md-4 col-md-offset-4">
                    <div class="input-group">
                        {{ form.as_p }}
                    </div>
                </div>
            </div>

            <div class="row1">
                <div class="col-md-4 col-md-offset-4">
                    <div class="form-group">
                        <a class="btn btn-secondary" href="{% url 'creartipous' proyecto_id %}">Cancelar</a>
                        <button class="btn btn-primary" type="submit">Guardar</button>
                    </div>
                </div>
            </div>

        </form>

    {% endblock %}

tipo_us/templates/tipous/detalle.html
{% extends 'proyecto/base.html' %}

{% block content %}

    <div class="col-sm">
         <a class="btn btn-primary float-right" href="javascript:history.back()">Atras</a>
    </div>

    <div class=" col-md-4 ">
        <dt>Nombre: </dt>
        <dd>{{ object.nombre }}</dd>
        <dt>Proyecto:</dt>
        <dd> {{ object.proyecto }} </dd>
        <dt>Flujos:</dt>
        {% for flujo in object.flujo_set.all  %}

            <dd> {{ forloop.counter }} - {{ flujo }}  </dd>

        {% endfor %}
        <dt>Campos personalizados: </dt>

        {% for tc in object.tipo_campo_set.all %}

            <dd> {{ forloop.counter }} -  {{ tc.campo.nombre_campo }}:  {{ tc.campo.imput_campo }} </dd>

        {% endfor %}

    </div>

{% endblock %}

tipo_us/templates/tipous/editar.html
{% extends 'proyecto/base.html' %}

{% block title %}
    <title>Registrar Tipo US</title>
{% endblock %}


{% block content %}

    <form method="post">
    {% csrf_token %}
        <div class="row1">
            <div class="col-md-4 col-md-offset-4">
                <div class="form-group" >
                    {{ form.as_p }}
                </div>
            </div>
        </div>

        <div class="row1">
            <div class="col-md-4 col-md-offset-4">
                <div class="form-group">
                    <button class="btn btn-primary" type="submit">Guardar</button>
                    <a class="btn btn-secondary" href="{% url 'ver_proyecto'  proyecto_id  %}">Cancelar</a>
                </div>
            </div>
        </div>

    </form>

{% endblock %}

tipo_us/templates/tipous/importar.html
{% extends 'proyecto/base.html' %}

{% block title %}
    <title>Importar Tipo US</title>
{% endblock %}


{% block content %}

    <form method="post">
    {% csrf_token %}
        <div class="row1">
            <div class="col-md-4 col-md-offset-4">
                <div class="form-group">
                    {{ form.as_p }}
                </div>
            </div>
        </div>

        <div class="row1">
            <div class="col-md-4 col-md-offset-4">
                <div class="form-group">

                    <button class="btn btn-primary" type="submit">Guardar</button>
                    <a class="btn btn-secondary" href="{% url 'listaimportar'  proyecto_id  %}">Cancelar</a>
                </div>
            </div>
        </div>

    </form>

{% endblock %}

tipo_us/templates/tipous/tipo_us_list.html
{% extends 'proyecto/base.html' %}

{% block title %}
    <title>Listar  TipoUS</title>
{% endblock %}

{% block content %}
    <div class="row float-right"><a class="btn btn-secondary" href="{% url 'ver_proyecto' proyecto_id %}">Atras</a></div>
    <h2 class="table-info"> TIPOS DE USER STORY </h2 >


    {% if messages %}
        <ul class = "messages">
            {% for message in messages %}
                <li {% if message.tags %} class = "{{ message.tags }}" {% endif %}> {{ message }} </li>
            {% endfor %}
        </ul>
    {% endif %}
    <div style="height:700px; overflow-y: scroll;">
    <table class="table table-bordered table-dark ">
        <thead>
            <tr>
                <td>NOMBRE</td>
                <td>PROYECTO</td>
                <td>FLUJOS</td>
                <td>CAMPOS_PERSONALIZADOS</td>
            </tr>

        </thead>
        <tbody class="table-bordered ">
            <nav class="container-fluid" >
                {% for tus in tipos_campos %}
                    <tr class="table-bordered" >
                        <td class="d-table-cell">{{ tus.nombre }} </td>
                        <td class="d-table-cell">{{ tus.proyecto }} </td>
                        <td>
                            {% for flujo in tus.flujo_set.all %}

                                <p>{{ flujo }}</p>
                                {% for us in us %}
                                    {% if flujo.id == us.flujo.id %}
                                        <a class="btn btn-secondary" href="{% url 'eliminar_flujo' flujo.pk %}">Eliminar</a>
                                    {% endif %}
                                {% endfor %}

                            {% endfor %}

                        </td>
                        <td class="align-center" >
                            {% for tcv in tus.tipo_campo_set.all %}

                                <p>{{ tcv.campo.nombre_campo }} : {{ tcv.valor }}</p>

                            {% endfor %}
                        </td>
                        <td align="right">
                            {% if tus.proyecto_id == proyecto_id %}
                                {#<a class="btn btn-link " href="{% url 'modificartipous'  proyecto_id tus.id  %}" >Modificar</a>#}
                                <a class="btn btn-link " href="{% url 'detalletipous'  proyecto_id tus.id  %}">ver detalles</a>
                            {% else %}
                                <a class="btn btn-link " href="{% url 'importartipous'  proyecto_id tus.id  %}" >Importar</a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </nav>

        </tbody>
    </table>
    </div>



{% endblock content %}